### ISSUE TITLE
Build error on Big Sur (x86-64)

### ISSUE THREAD

**Issue by t-scale** [asb2m10/plugincollider#3]
Hey! Amazing project :)
I'm having some issues building the plugin.
Here are the steps to reproduce:
- When building SC from the selected branch in the repo, I get several CMake-related errors. But when switching to the current `develop` branch, everything builds fine.
- I've tried building the plugin with both GCC and Clang (tried different versions as well) without luck. I've tried building in Xcode but same result.
This is the error I get: `library not found for -lsndfile` although I've libsndfile installed (from homebrew).
I'm not sure if this is an issue or if this is related to building SC from the `develop` branch? (or both?)

**Comment by asb2m10** [comment]
- Yes, for now develop branch for supercollider is required to build the solution correctly.
- You can simply comment out the line 242 with sndfile on mac OS, it should be built out of the box. It is with Linux that it is required. I will look how I can solve this issue, it seems to be a sndfile detection problem with cmake. https://github.com/asb2m10/plugincollider/blob/eab611943cd9826328d60ae84441f05c85e72a98/CMakeLists.txt#L242

**Comment by t-scale** [comment]
ah! that's built now :)
